name: Run test.py

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '55 23 * * *'   # 每天 UTC 23:55 = 北京时间次日 07:55 自动运行

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run test.py and save log
        run: |
          python test.py > output.log 2>&1 || true

      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-log
          path: output.log
