name: Run test.py

on:
  push:                # 每次 push 到 main 分支时自动运行
    branches: [ main ]
  workflow_dispatch:   # 也可以在 Actions 页面手动点运行

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run test.py and save log
        run: |
          python test.py > output.log 2>&1

      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: test-log
          path: output.log
